[package]
name = "blackarch-devtools"
version = "0.3.0"
authors = ["Eduard Toloza <tolosaeduard@gmail.com>"]
edition = "2018"

[dependencies]
termcolor = "1.0.4"
clap = {version = "2.33.0", features = ["yaml"]}
